# Generated by Django 4.2.7 on 2023-12-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_kino_trailer_url_actor_best_actor_filmcount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kino',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Трейлер'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='best',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Лучшие фильмы: '),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя/Фамилия'),
        ),
        migrations.AlterField(
            model_name='director',
            name='best',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Лучшие фильмы: '),
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя/Фамилия'),
        ),
    ]
