# Generated by Django 4.2.7 on 2023-12-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_review_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
