# Generated by Django 4.2.7 on 2023-12-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_rename_avtive_comment_active_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='kino',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='podpiska',
            name='level',
            field=models.CharField(choices=[('free', 'БЕСПЛАТНАЯ'), ('based', 'БАЗОВАЯ'), ('super', 'ПРЕМИУМ')], max_length=20, verbose_name='Подписка'),
        ),
    ]
